// Package dbmodel Code generated by sql2struct.
package dbmodel

import "time"

// User 用户表
type User struct {
	ID         int64     `gorm:"column:id" json:"id,omitempty"`
	UserID     int64     `gorm:"column:user_id" json:"user_id,omitempty"`         // 用户 id
	Email      string    `gorm:"column:email" json:"email,omitempty"`             // 用户邮箱
	Phone      string    `gorm:"column:phone" json:"phone,omitempty"`             // 手机号
	Role       uint8     `gorm:"column:role" json:"role,omitempty"`               // 用户角色  1:超级管理员 2:其他
	WebsiteURL string    `gorm:"column:website_url" json:"website_url,omitempty"` // 个人主页
	Remark     string    `gorm:"column:remark" json:"remark,omitempty"`           // 备注
	CreatedAt  time.Time `gorm:"column:created_at" json:"created_at,omitempty"`   // 创建时间
	UpdatedAt  time.Time `gorm:"column:updated_at" json:"updated_at,omitempty"`   // 更新时间
	DeletedAt  time.Time `gorm:"column:deleted_at" json:"deleted_at,omitempty"`   // 移除时间
}

// TableName the name of table in database
func (t *User) TableName() string {
	return "user"
}
